apiVersion: v1
data:
  hashrings.json: |-
    [
      {
        "hashring": "default",
        "tenants": [

        ]
      }
    ]
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: kubernetes-controller
    app.kubernetes.io/instance: benchmark-thanos-receive-controller
    app.kubernetes.io/name: thanos-receive-controller
    app.kubernetes.io/part-of: telemeter-benchmark
    app.kubernetes.io/version: master-2020-02-06-b66e0c8
  name: benchmark-thanos-receive-controller-tenants
  namespace: telemeter-benchmark
