---
apiVersion: v1
kind: Namespace
metadata:
  name: standalone-metrics-collector
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    service.alpha.openshift.io/inject-cabundle: "true"
  name: metrics-collector-serving-certs-ca-bundle
  namespace: standalone-metrics-collector
data:
  service-ca.crt: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: endpoint-observability-operator-sa
  namespace: standalone-metrics-collector
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: standalone-metrics-collector
subjects:
  - kind: ServiceAccount
    name: endpoint-observability-operator-sa
    namespace: standalone-metrics-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
---
apiVersion: v1
kind: Secret
metadata:
  name: observability-managed-cluster-certs
  namespace: standalone-metrics-collector
data:
  ca.crt:
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURhRENDQWxDZ0F3SUJBZ0lSQU9hcXFQU3QzKzdwSUNGMmhoZCs4dVF3RFFZSktvWklodmNOQVFFTEJRQXcKUlRFVk1CTUdBMVVFQ2hNTVkyVnlkQzF0WVc1aFoyVnlNU3d3S2dZRFZRUURFeU52WW5ObGNuWmhZbWxzYVhSNQpMWE5sY25abGNpMWpZUzFqWlhKMGFXWnBZMkYwWlRBZUZ3MHlNVEEyTVRFeE5ESTNORFZhRncweU5qQTJNVEF4Ck5ESTNORFZhTUVVeEZUQVRCZ05WQkFvVERHTmxjblF0YldGdVlXZGxjakVzTUNvR0ExVUVBeE1qYjJKelpYSjIKWVdKcGJHbDBlUzF6WlhKMlpYSXRZMkV0WTJWeWRHbG1hV05oZEdVd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQQpBNElCRHdBd2dnRUtBb0lCQVFESm9hOUxMSjl1cSsycmllZjhHNDFLRCtXSGNQeFhzdTNVanIxejU2Z05MY0JkCnY2SjBrT2wxNnNZaTM5dkRVT2lJVS80N2JQNysvd2dSWlYvY2F5ejFUMWlIU3ZNc2VLWHphOENRQXRxZFpKeHoKL3ZtMGJ3WGRBcldtS3VNdHZNRUovWmUrSUxhbU92NUtscnFmOHhjUDV6UVhRZURoYnBFaUU5ZjJYV1F6M3dvcwpWVjd1TFF0bDhSaTdXdGtZcW5KQWpyQy9VV1M4a3dtVzhqVldYVVFDbmpySVlkckRsbXYyM3VqSGJLOFNla3NoCitSdkZWN2lScVNQYUZyRVVMcldmdzlWNGZxTHF3OGlTY0FORFNhQzdmU0hVOVpsaCs2WCt1OXBKK1NiL2RWMkQKbFAwM1NOR2pBd01vL1V2dllEN2R1RVJUK09iMFZuWmlaMmd0Q1hwVEFnTUJBQUdqVXpCUk1BNEdBMVVkRHdFQgovd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01DNEdBMVVkRVFRbk1DV0NJMjlpYzJWeWRtRmlhV3hwCmRIa3RjMlZ5ZG1WeUxXTmhMV05sY25ScFptbGpZWFJsTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCRVlHWi8KRTF5Ty9PMkRCYmY5WEIvWkZNVUZZUGZxN3FzaWFHemc2Z3VkTytaR1hQZFQybytIUFlHMC9wZUgybzZpNVBhcgpLVXlHaUk2QmNwSHRqdVB4SlQvUDF5a2pibThYODEzZFlWaEEzMGpyOWxIMWJ5azgvd1lLVWVQeXRjMFhOZEQvCjk3U3NhM2hUbUVrbmhHM24xSFVJUVlMS3pHNmtjNG1XdENqcVp3Ym9Obmdza1ptS1QzaTFNeVpVTFFyN3BVV3EKMUIxeHl6VU83WkQra2Mzb1Ura2NibmdvWk9hMmc0d042Zm1KNHdEM1FlNnJGbjJLSkh4WDF4emRZaWwxV2xPWgpiclErbnhzTXhQWWtZN24zYXBFT0JOWVRnSWg4aWNiaDFGRmYyWXU5U3ozQWFZODZjN1NLU3NidmFCZ0R6bGt0ClZKZ1RKZWhOWmllUUFUMzkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo= 
  tls.crt:
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURURENDQWpTZ0F3SUJBZ0lRU0lNeW4xVjlSVFdvcVU3RHBYbldPekFOQmdrcWhraUc5dzBCQVFzRkFEQkYKTVJVd0V3WURWUVFLRXd4alpYSjBMVzFoYm1GblpYSXhMREFxQmdOVkJBTVRJMjlpYzJWeWRtRmlhV3hwZEhrdApZMnhwWlc1MExXTmhMV05sY25ScFptbGpZWFJsTUI0WERUSXhNRFl4TVRFME1qZ3hNRm9YRFRJeU1EWXhNVEUwCk1qZ3hNRm93UURFVk1CTUdBMVVFQ2hNTVkyVnlkQzF0WVc1aFoyVnlNUXd3Q2dZRFZRUUxFd05oWTIweEdUQVgKQmdOVkJBTVRFRzFqTFd4dlkyRnNMV05zZFhOMFpYSXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBdwpnZ0VLQW9JQkFRQ3lGeklOLytGQTF6cG1OWXEyU2pwQWM0Z3BIeks5anBoejZSUG5QRWtzWmFSQ3BMSUkzUWxsClVGRjlPMlZ3RnJkYTRzUi8wRnVpcU5sd0ltSjcrV3h0VGhrcThrRjM2bHZBZnZJWDEydllRcTFpRWZzVEdmdHkKUUdxSkFEdkppNGpiTDRFQkY5OGVLcGM4OHc4VmxyLzZNYjFCcE9EbjBWN0RCRnJRV1FyQkNLbkFUVmFZSThaUApJdnFPaGFibkFUUHZjVGtVamJBbDhJanoyaGYxU0VFNCtwanZHNHI5cWJXRkE0akZhRVFzRTlacXRlRXNyQ09TCkx4WUJLQndTc1QyV2lnR2MrMW1NSWNwcXpzVnF0anIwNm1yOU5tMmx4T1pFS2dQT3hMV3haQjJZa2d2WnAzdUgKanJBeFJkcjlKdzc4dW80THVyQzA5NkJRSS91SVVlRlBBZ01CQUFHalBUQTdNQTRHQTFVZER3RUIvd1FFQXdJRgpvREFNQmdOVkhSTUJBZjhFQWpBQU1Cc0dBMVVkRVFRVU1CS0NFRzFqTFd4dlkyRnNMV05zZFhOMFpYSXdEUVlKCktvWklodmNOQVFFTEJRQURnZ0VCQUtUOFkzckRFcU9WSXVPSTJRLzQxUno1Uk9pamdlcVFMMXZYYlBDTEEvNlAKdUdKQ202WUdxSTNvZG53OW9qcTRlQzVoL3MyanE4Y0pMa3gwbmZ2bkp6eTFXMDZoMU4xSDNjUzhnZEljZlVJbgp0NXBlSmQzWDFGcEdqaCtJWG5kajB2QnQxQlFZNTJFMWMyUzNMeVI4VEpaOTRKeCtKY0xoczBxa0o0SnpTMDdtCkV5cExKSE5MU1dPZHhPRjl0TS84NVlZbzFwUGxNUDc1TjdqYXNSc1lReUNpMXZiOG0xU2dMSzNnbVJtMWFRbzUKWFVseHRCa0tXa3QrQ3YwbE1VNFhBVHdoZ2FQZzI0Z2N6ZDRSRE4xaEQ0akUzUGZjWlJadTdsYzl2ZzJqVmRYTgpVQ3laUkR0ZkoybFhMTENlUHAxVDV4RmMzSE1CYlhhR1MwTFZzZW5COUN3PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg== 
  tls.key:
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBc2hjeURmL2hRTmM2WmpXS3RrbzZRSE9JS1I4eXZZNlljK2tUNXp4SkxHV2tRcVN5CkNOMEpaVkJSZlR0bGNCYTNXdUxFZjlCYm9xalpjQ0ppZS9sc2JVNFpLdkpCZCtwYndIN3lGOWRyMkVLdFloSDcKRXhuN2NrQnFpUUE3eVl1STJ5K0JBUmZmSGlxWFBQTVBGWmEvK2pHOVFhVGc1OUZld3dSYTBGa0t3UWlwd0UxVwptQ1BHVHlMNmpvV201d0V6NzNFNUZJMndKZkNJODlvWDlVaEJPUHFZN3h1Sy9hbTFoUU9JeFdoRUxCUFdhclhoCkxLd2praThXQVNnY0VyRTlsb29CblB0WmpDSEthczdGYXJZNjlPcHEvVFp0cGNUbVJDb0R6c1Mxc1dRZG1KSUwKMmFkN2g0NndNVVhhL1NjTy9McU9DN3F3dFBlZ1VDUDdpRkhoVHdJREFRQUJBb0lCQVFDRFJiM0x1L1dhQ2d3dQpFd0Z3WlQ2VEM1WXVXYVRaUFNiN0thOVdINFlBaDl1UWxEMzNjcGJlYTFubDZjWlgzU2JDZzYwOFdhVnlQT3dxClQrNHdYQ2FrVzVFSnF4Qy9CNjBpTTNEWVNoNWdocVd2U0htK0ZzVFY3czJZdHVkYkpOTjRYWWZGK29hb2dkU0IKUk5pMW5TMWRpeFJxTXRMbGpkcy8vUkhEeWg2M01pUWQ0RHdIR1hpWjVoc1lvMTF1M1JuODhiQUZRR0kvUm12NApiNWloWk1NT1BVRmkrT1pEbStOWGNiUHhIMDBPaFhtN2lIcEVmQ21DWFUrNFBhY2FRMityc1FDKzluVTdVYzV4CnNCNk5rcTErWW1EMlNOdHFML3lERXVsOFRUNTVjc0pWU1plZ05KQmZ0b1FwNTF1SnVkTWhqQmxQMzVwRFM1ZWcKL2JDanZIbWhBb0dCQU1nbnZxTW1LTTFrVC83R1kzSzVMbGszOG5YUndNWWQwbTJyOWNvZnZKZzBOb1Myb0NRegp6TmVEK1ZpRWhTaGZCWHFnc2greW5NSjZRVUtHVWxjckxuckpGY1BMNlZjbk9XRGtYQmZrbFVvU3JnR3BHcTc5ClJYOHMwOUs3UEdLd2lFaHJMYjdySkhSeFA3Q2lXeHdFQzUrMXBIVTJVUXo5LzVvdUVEZS93TVFGQW9HQkFPUEgKZHhrblMxVThKTmVnTkwyUmRYUllGbmVCNGF0RXJMOVB6UHM1Rksxais0M3B5UlZJT3RHNy9wNDF6aEcrYXFFTwpmZEpTMVFpZnFXUGVJeDhrU281K0FNR1VVclBaUTlrY1RLWUlSZy81Zlhndk1iZWxualdVUnRlRmxMQlNKTlppCm84Mkd1by9FRnc4b1FzckF4MWNqSThaN2NrYlZlNitxaWQ0YVhJUkRBb0dCQUxXVHlOQTlSL3E4ckEyWGNKU2QKQmowT0VqbHNaaFBVN2hkc1R2aGt2alRkK1MrQWRkc2gydzBRdnQzY3F1Z3ErODk1aE41WXJQbUk2emNzbi9wUQpSRVJEdENrQ0RkZHcwQTdrVzkrWkVRNDN6Ly9WcDAxa211MTZmMWZIWUVxdmw1TUxHRjhBOXZ0ajJjR21LRDFNCk5qZFhFN0Q1NjZGN3M2dnRhZTBKV2hqNUFvR0JBTVlBR1Faemd1ZTMzV3JXNTZHMTlQektxZFQrd1RXSkFBVloKa0J6OTFIeVpBZzJ0b005d056a2tDMFJxRHhTYmlzTXYvcTI2dFZiR3U0K0ZoTkJJVXNza3V2R0xSb3p5R3lsNgprU0p1NU1CMEp0NDNZQ2Q4djFkaDZtYmt4b2l6RHpTUkVFVFRqZzcwN1BxUEMraUZ4WUo0bUZ1cjZYMnJpOVg3CkQ5ZFM0UU5UQW9HQUFhNHVMZVZMV2R5RVpSWU1WNkFJeDRVK2JMcm5IZUJmenI5a2xBNE40dmZmNlArUE5QSFoKOHp4ZW9oNzM3bk9CN09reGNleU96MVYxL2lIUVkvTFhGR3VOcEdiaXROc2p5ZWEvM01oVGRlRTMrTGdHVzB4ZQpyNGsxeC93Y2Vkcm9WRVVOem1WWTZPMUE4bi96T2V2R3YrbXFxRWpjaDdtVVJubUQwa3ZjeHFRPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo= 
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: standalone-metrics-collector
  namespace: standalone-metrics-collector
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: standalone-metrics-collector
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: standalone-metrics-collector
    spec:
      containers:
      - command:
        - /usr/bin/telemeter-client
        - --from=$(FROM)
        - --to-upload=$(TO)
        - --from-ca-file=/etc/serving-certs-ca-bundle/service-ca.crt
        - --from-token-file=/var/run/secrets/kubernetes.io/serviceaccount/token
        - --interval=60s
        - --label="cluster=cyang-test"
        - --label="clusterID=762756be-45b1-41dc-8631-abc40a212f11"
        - --limit-bytes=1073741824
        - --match={__name__=":node_memory_MemAvailable_bytes:sum"}
        - --match={__name__="ALERTS"}
        - --match={__name__="apiserver_request_count"}
        - --match={__name__="apiserver_request_latencies_summary_count"}
        - --match={__name__="apiserver_request_latencies_summary_sum"}
        - --match={__name__="authenticated_user_requests"}
        - --match={__name__="authentication_attempts"}
        - --match={__name__="cluster:capacity_cpu_cores:sum"}
        - --match={__name__="cluster:capacity_memory_bytes:sum"}
        - --match={__name__="cluster:container_cpu_usage:ratio"}
        - --match={__name__="cluster:container_spec_cpu_shares:ratio"}
        - --match={__name__="cluster:cpu_usage_cores:sum"}
        - --match={__name__="cluster:memory_usage:ratio"}
        - --match={__name__="cluster:memory_usage_bytes:sum"}
        - --match={__name__="cluster:usage:resources:sum"}
        - --match={__name__="cluster_infrastructure_provider"}
        - --match={__name__="cluster_version"}
        - --match={__name__="cluster_version_payload"}
        - --match={__name__="container_cpu_cfs_periods_total"}
        - --match={__name__="container_cpu_cfs_throttled_periods_total"}
        - --match={__name__="container_spec_cpu_quota"}
        - --match={__name__="coredns_dns_request_count_total"}
        - --match={__name__="coredns_dns_request_duration_seconds_sum"}
        - --match={__name__="coredns_dns_request_type_count_total"}
        - --match={__name__="coredns_dns_response_rcode_count_total"}
        - --match={__name__="etcd_debugging_mvcc_db_total_size_in_bytes"}
        - --match={__name__="etcd_debugging_snap_save_total_duration_seconds_sum"}
        - --match={__name__="etcd_disk_backend_commit_duration_seconds_bucket"}
        - --match={__name__="etcd_disk_backend_commit_duration_seconds_sum"}
        - --match={__name__="etcd_disk_wal_fsync_duration_seconds_bucket"}
        - --match={__name__="etcd_disk_wal_fsync_duration_seconds_sum"}
        - --match={__name__="etcd_object_counts"}
        - --match={__name__="etcd_network_client_grpc_received_bytes_total"}
        - --match={__name__="etcd_network_client_grpc_sent_bytes_total"}
        - --match={__name__="etcd_network_peer_received_bytes_total"}
        - --match={__name__="etcd_network_peer_sent_bytes_total"}
        - --match={__name__="etcd_server_client_requests_total"}
        - --match={__name__="etcd_server_has_leader"}
        - --match={__name__="etcd_server_health_failures"}
        - --match={__name__="etcd_server_leader_changes_seen_total"}
        - --match={__name__="etcd_server_proposals_failed_total"}
        - --match={__name__="etcd_server_proposals_pending"}
        - --match={__name__="etcd_server_proposals_committed_total"}
        - --match={__name__="etcd_server_proposals_applied_total"}
        - --match={__name__="etcd_server_quota_backend_bytes"}
        - --match={__name__="grpc_server_started_total"}
        - --match={__name__="haproxy_backend_connection_errors_total"}
        - --match={__name__="haproxy_backend_connections_total"}
        - --match={__name__="haproxy_backend_current_queue"}
        - --match={__name__="haproxy_backend_http_average_response_latency_milliseconds"}
        - --match={__name__="haproxy_backend_max_sessions"}
        - --match={__name__="haproxy_backend_response_errors_total"}
        - --match={__name__="haproxy_backend_up"}
        - --match={__name__="http_requests_total"}
        - --match={__name__="instance:node_filesystem_usage:sum"}
        - --match={__name__="instance:node_cpu_utilisation:rate1m"}
        - --match={__name__="instance:node_load1_per_cpu:ratio"}
        - --match={__name__="instance:node_memory_utilisation:ratio"}
        - --match={__name__="instance:node_network_receive_bytes_excluding_lo:rate1m"}
        - --match={__name__="instance:node_network_receive_drop_excluding_lo:rate1m"}
        - --match={__name__="instance:node_network_transmit_bytes_excluding_lo:rate1m"}
        - --match={__name__="instance:node_network_transmit_drop_excluding_lo:rate1m"}
        - --match={__name__="instance:node_num_cpu:sum"}
        - --match={__name__="instance:node_vmstat_pgmajfault:rate1m"}
        - --match={__name__="instance_device:node_disk_io_time_seconds:rate1m"}
        - --match={__name__="instance_device:node_disk_io_time_weighted_seconds:rate1m"}
        - --match={__name__="kube_daemonset_status_desired_number_scheduled"}
        - --match={__name__="kube_daemonset_status_number_unavailable"}
        - --match={__name__="kube_node_spec_unschedulable"}
        - --match={__name__="kube_node_status_allocatable"}
        - --match={__name__="kube_node_status_allocatable_cpu_cores"}
        - --match={__name__="kube_node_status_allocatable_memory_bytes"}
        - --match={__name__="kube_node_status_capacity"}
        - --match={__name__="kube_node_status_capacity_pods"}
        - --match={__name__="kube_node_status_capacity_cpu_cores"}
        - --match={__name__="kube_node_status_condition"}
        - --match={__name__="kube_pod_container_resource_limits"}
        - --match={__name__="kube_pod_container_resource_limits_cpu_cores"}
        - --match={__name__="kube_pod_container_resource_limits_memory_bytes"}
        - --match={__name__="kube_pod_container_resource_requests"}
        - --match={__name__="kube_pod_container_resource_requests_cpu_cores"}
        - --match={__name__="kube_pod_container_resource_requests_memory_bytes"}
        - --match={__name__="kube_pod_info"}
        - --match={__name__="kube_pod_owner"}
        - --match={__name__="kube_resourcequota"}
        - --match={__name__="kubelet_running_container_count"}
        - --match={__name__="kubelet_runtime_operations"}
        - --match={__name__="kubelet_runtime_operations_latency_microseconds"}
        - --match={__name__="kubelet_volume_stats_available_bytes"}
        - --match={__name__="kubelet_volume_stats_capacity_bytes"}
        - --match={__name__="kube_persistentvolume_status_phase"}
        - --match={__name__="machine_cpu_cores"}
        - --match={__name__="machine_memory_bytes"}
        - --match={__name__="mixin_pod_workload"}
        - --match={__name__="namespace:kube_pod_container_resource_requests_cpu_cores:sum"}
        - --match={__name__="namespace:kube_pod_container_resource_requests_memory_bytes:sum"}
        - --match={__name__="namespace:container_memory_usage_bytes:sum"}
        - --match={__name__="namespace_cpu:kube_pod_container_resource_requests:sum"}
        - --match={__name__="namespace_workload_pod:kube_pod_owner:relabel"}
        - --match={__name__="node_cpu_seconds_total"}
        - --match={__name__="node_filesystem_avail_bytes"}
        - --match={__name__="node_filesystem_free_bytes"}
        - --match={__name__="node_filesystem_size_bytes"}
        - --match={__name__="node_memory_MemAvailable_bytes"}
        - --match={__name__="node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate"}
        - --match={__name__="node_netstat_Tcp_OutSegs"}
        - --match={__name__="node_netstat_Tcp_RetransSegs"}
        - --match={__name__="node_netstat_TcpExt_TCPSynRetrans"}
        - --match={__name__="up"}
        - --match={__name__="cluster_monitoring_operator_reconcile_errors_total"}
        - --match={__name__="cluster_monitoring_operator_reconcile_attempts_total"}
        - --match={__name__="cluster_operator_conditions"}
        - --match={__name__="cluster_operator_up"}
        - --match={__name__="workqueue_queue_duration_seconds_bucket",job="apiserver"}
        - --match={__name__="workqueue_adds_total",job="apiserver"}
        - --match={__name__="workqueue_depth",job="apiserver"}
        - --match={__name__="go_goroutines",job="apiserver"}
        - --match={__name__="process_cpu_seconds_total",job="apiserver"}
        - --match={__name__="process_resident_memory_bytes",job="apiserver"}
        - --match={__name__="container_memory_cache",container!=""}
        - --match={__name__="container_memory_rss",container!=""}
        - --match={__name__="container_memory_swap",container!=""}
        - --match={__name__="container_memory_working_set_bytes",container!=""}
        - --rename="mixin_pod_workload=namespace_workload_pod:kube_pod_owner:relabel"
        - --rename="namespace:kube_pod_container_resource_requests_cpu_cores:sum=namespace_cpu:kube_pod_container_resource_requests:sum"
        - --recordingrule={"name":"apiserver_request_duration_seconds:histogram_quantile_99","query":"histogram_quantile(0.99,sum(rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\", verb!=\"WATCH\"}[5m])) by (verb,le))"}
        - --recordingrule={"name":"apiserver_request_duration_seconds:histogram_quantile_99:instance","query":"histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\", verb!=\"WATCH\"}[5m])) by (le, instance))"}
        - --recordingrule={"name":"sum:apiserver_request_total:1h","query":"sum(rate(apiserver_request_total{job=\"apiserver\"}[1h])) by(code, instance)"}
        - --recordingrule={"name":"sum:apiserver_request_total:5m","query":"sum(rate(apiserver_request_total{job=\"apiserver\"}[5m])) by(code, instance)"}
        - --recordingrule={"name":"rpc_rate:grpc_server_handled_total:sum_rate","query":"sum(rate(grpc_server_handled_total{job=\"etcd\",grpc_type=\"unary\",grpc_code!=\"OK\"}[5m]))"}
        - --recordingrule={"name":"active_streams_watch:grpc_server_handled_total:sum","query":"sum(grpc_server_started_total{job=\"etcd\",grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{job=\"etcd\",grpc_service=\"etcdserverpb.Watch\",grpc_type=\"bidi_stream\"})"}
        - --recordingrule={"name":"active_streams_lease:grpc_server_handled_total:sum","query":"sum(grpc_server_started_total{job=\"etcd\",grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"}) - sum(grpc_server_handled_total{job=\"etcd\",grpc_service=\"etcdserverpb.Lease\",grpc_type=\"bidi_stream\"})"}
        env:
        - name: FROM
          value: https://prometheus-k8s.openshift-monitoring.svc:9091
        - name: TO
          value: https://observatorium-api-open-cluster-management-observability.apps.obs-china-aws-480-jhxz8.dev05.red-chesterfield.com/api/metrics/v1/default/api/v1/receive
        - name: STANDALONE
          value: "true"
        image: quay.io/open-cluster-management/metrics-collector:2.3.0-SNAPSHOT-2021-06-08-08-29-28
        imagePullPolicy: Always
        name: metrics-collector
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tlscerts/ca
          name: observability-managed-cluster-certs
        - mountPath: /tlscerts/certs
          name: observability-managed-cluster-certs
        - mountPath: /etc/serving-certs-ca-bundle
          name: serving-certs-ca-bundle
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: endpoint-observability-operator-sa
      serviceAccountName: endpoint-observability-operator-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - name: observability-managed-cluster-certs
        secret:
          defaultMode: 420
          secretName: observability-managed-cluster-certs
      - configMap:
          defaultMode: 420
          name: metrics-collector-serving-certs-ca-bundle
        name: serving-certs-ca-bundle