apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: monitoring-client
  name: monitoring-client
  namespace: open-cluster-management-monitoring
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: monitoring-client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: monitoring-client
    spec:
      containers:
      - command:
        - /usr/bin/telemeter-client
        - --id=$(ID)
        - --from=$(FROM)
        - --from-ca-file=/etc/serving-certs-ca-bundle/service-ca.crt
        - --from-token-file=/var/run/secrets/kubernetes.io/serviceaccount/token
        - --to=url
        - --to-upload=$(TO)
        - --listen=localhost:8080
        - --match={__name__="up"}
        - --limit-bytes=5242880
        - --log-level=debug
        - --verbose=true
        env:
        - name: ANONYMIZE_LABELS
        - name: FROM
          value: https://prometheus-k8s.openshift-monitoring.svc:9091
        - name: ID
          value: 9d9de635-6a7a-4da3-91ae-7b584b7a84e3
        - name: TO
          value: http://observatorium-api-open-cluster-management-monitoring.apps.marco.dev05.red-chesterfield.com/api/metrics/v1/write
        - name: HTTP_PROXY
        - name: HTTPS_PROXY
        - name: NO_PROXY
        image: blue0/telemeter:latest
        imagePullPolicy: Always
        name: telemeter-client
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 1m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - name: certs
            readOnly: true
            mountPath: /etc/certs
          - mountPath: /etc/serving-certs-ca-bundle
            name: serving-certs-ca-bundle
            readOnly: false
      volumes:
        - name: certs
          secret:
            secretName: client-certs
        - configMap:
            name: telemeter-client-serving-certs-ca-bundle
          name: serving-certs-ca-bundle
