apiVersion: v1
data:
  rbac.yaml: |-
    "roleBindings":
    - "name": "test-mtls"
      "roles":
      - "read-write"
      "subjects":
      - "kind": "user"
        "name": "up"
    "roles":
    - "name": "read-write"
      "permissions":
      - "write"
      - "read"
      "resources":
      - "metrics"
      "tenants":
      - "test-mtls"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: observability-observatorium
    app.kubernetes.io/name: observatorium-api
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: latest
  name: observability-observatorium-observatorium-api
  namespace: open-cluster-management-monitoring